steps:
# This step is to build the docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/hello-world-360303/github/betrand2470/gcp-node-app:$SHORT_SHA', '.' ]

# This step is to push the iamge to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/hello-world-360303/github/betrand2470/gcp-node-app:$SHORT_SHA' ]
  
#  This step is to run glcoud deploy to deploy the container image.
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'hello-world-360303', '--image=gcr.io/hello-world-360303/github/betrand2470/gcp-node-app:$SHORT_SHA', '--region=us-central1', '--platform=managed']